import {env} from 'cloudflare:workers';
import {sample,State,Order} from '@/lib/model';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store',...headers}});
function workspace(req:Request){const id=req.headers.get('x-rq-workspace')||'nimbus';return ['nimbus','aurora','circuit'].includes(id)?id:'nimbus';}
function scoped(tenant:string,id:string){return id==='nimbus'?tenant:tenant+'::'+id;}
function identity(req:Request){const user=req.headers.get('oai-authenticated-user-id');if(user)return user;const h=new URL(req.url).hostname;return ['localhost','127.0.0.1','::1','[::1]','terminal.local'].includes(h)?'local-demo':null;}
const sampleJsonCache=new Map<string,string>();
const schemaReady=new WeakMap<object,Promise<void>>();
function getSampleJson(id:string){let s=sampleJsonCache.get(id);if(!s){s=JSON.stringify(sample(id));sampleJsonCache.set(id,s);}return s;}
async function ensureSchema(db:D1Database){let p=schemaReady.get(db);if(!p){p=(async()=>{await db.prepare('CREATE TABLE IF NOT EXISTS sessions (token text PRIMARY KEY NOT NULL, tenant text NOT NULL, role text NOT NULL, expires integer NOT NULL)').bind().run();await db.prepare('CREATE TABLE IF NOT EXISTS workspaces (tenant text PRIMARY KEY NOT NULL, body text NOT NULL, version integer DEFAULT 1 NOT NULL)').bind().run();})();schemaReady.set(db,p);}return p;}
function viewState(raw:State,role:string):State{if(role!=='RIDER')return raw;return {orders:raw.orders.filter(o=>o.rider==='rid_1'),actions:[],audit:[]};}
async function auth(req:Request){const db=env.DB;if(!db)throw Error('Storage unavailable');await ensureSchema(db);const tenant=identity(req);if(!tenant)return null;const token=(req.headers.get('cookie')||'').match(/(?:^|;\s*)rq_session=([^;]+)/)?.[1];if(!token)return null;return await db.prepare('SELECT role, tenant FROM sessions WHERE token = ? AND tenant = ? AND expires > ?').bind(token,tenant,Date.now()).first<{role:string;tenant:string}>();}
async function load(tenant:string,id='nimbus'){const db=env.DB!;await ensureSchema(db);let row=await db.prepare('SELECT body,version FROM workspaces WHERE tenant=?').bind(tenant).first<{body:string;version:number}>();if(!row){const body=getSampleJson(id);await db.prepare('INSERT OR IGNORE INTO workspaces (tenant,body,version) VALUES (?,?,1)').bind(tenant,body).run();row=(await db.prepare('SELECT body,version FROM workspaces WHERE tenant=?').bind(tenant).first<{body:string;version:number}>())??{body,version:1};}return row;}
export async function GET(req:Request){try{const a=await auth(req);if(!a)return json({error:'Please enter the demo workspace.'},401);const url=new URL(req.url);if(a.role==='RIDER'&&url.searchParams.get('scope')==='seller')return json({error:'Seller access required'},403);const wid=workspace(req);const dataTenant=scoped(a.tenant,wid);const row=await load(dataTenant,wid);const state=viewState(JSON.parse(row.body),a.role);return json({state,role:a.role,app_env:'demo',workspace:wid,version:row.version});}catch(e){console.error(e);return json({error:'Workspace storage is unavailable. Please retry.'},503);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid origin'},403);if(Number(req.headers.get('content-length')||0)>2_000_000)return json({error:'File too large'},413);const b:any=await req.json();const tenant=identity(req);if(!tenant)return json({error:'Sign in to this private site first'},401);const db=env.DB!;await ensureSchema(db);if(b.op==='login'||b.op==='switch'){if(b.op==='switch'&&!await auth(req))return json({error:'Session required'},401);if(!['SELLER','RIDER'].includes(b.role))return json({error:'Invalid role'},422);const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO sessions (token,tenant,role,expires) VALUES (?,?,?,?)').bind(token,tenant,b.role,Date.now()+86400000).run();const wid=workspace(req);const row=await load(scoped(tenant,wid),wid);return json({ok:true,state:viewState(JSON.parse(row.body),b.role),role:b.role,app_env:'demo',workspace:wid,version:row.version},200,{'Set-Cookie':`rq_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=86400${new URL(req.url).protocol==='https:'?'; Secure':''}`});}
const a=await auth(req);if(!a)return json({error:'Session expired'},401);if(a.role==='RIDER'&&b.op!=='delivery')return json({error:'Seller access required'},403);const wid=workspace(req);const dataTenant=scoped(a.tenant,wid);const row=await load(dataTenant,wid);const state:State=JSON.parse(row.body);let result:Record<string,unknown>={ok:true};const now=new Date().toISOString();
if(b.op==='delivery'){const o=state.orders.find(o=>o.id===b.id&&(a.role!=='RIDER'||o.rider==='rid_1'));if(!o)return json({error:'Delivery not found'},404);if(!['DELIVERED','COD_REJECTED','NDR'].includes(b.outcome))return json({error:'Invalid outcome'},422);if(['DELIVERED','RETURN_REQUESTED','RTO'].includes(o.status))return json({error:'This delivery is already closed'},409);if(b.outcome==='COD_REJECTED'&&o.payment==='PREPAID')return json({error:'This is a prepaid order'},422);if(b.outcome!=='DELIVERED'&&(!b.reason||String(b.reason).trim().length<3))return json({error:'A reason is required'},422);o.status=b.outcome;o.attempts.push({at:now,outcome:b.outcome,reason:String(b.reason||'').slice(0,300)});}
else if(b.op==='review'){const o=state.orders.find(o=>o.id===b.id);if(!o)return json({error:'Order not found'},404);if(!['DELIVERED','RETURN_REQUESTED'].includes(o.status))return json({error:'Reviews require a completed delivery'},422);if(!Number.isInteger(b.rating)||b.rating<1||b.rating>5)return json({error:'Choose a rating from 1 to 5'},422);o.review={rating:b.rating,tags:(Array.isArray(b.tags)?b.tags:[]).filter((x:unknown)=>typeof x==='string').slice(0,4)};}
else if(b.op==='propose'){const o=state.orders.find(o=>o.id===b.id);if(!o)return json({error:'Order not found'},404);if(state.actions.some(x=>x.order===o.id&&x.status==='PENDING_APPROVAL'))return json({error:'An approval is already pending for this order'},409);state.actions.push({id:'act_'+crypto.randomUUID(),order:o.id,type:o.status==='RETURN_REQUESTED'?'REFUND_AFTER_QC':'VERIFY_COD',status:'PENDING_APPROVAL',version:1,created:now});}
else if(b.op==='decision'){const act=state.actions.find(x=>x.id===b.id);if(!act)return json({error:'Action not found'},404);if(act.status!=='PENDING_APPROVAL'||act.version!==b.version)return json({error:'This action changed. Refresh before deciding.'},409);if(!['APPROVE','REJECT'].includes(b.decision))return json({error:'Invalid decision'},422);act.status=b.decision==='APPROVE'?'EXECUTED':'REJECTED';act.version++;}
else if(b.op==='outcome'){const act=state.actions.find(x=>x.id===b.id);if(!act||act.status!=='EXECUTED')return json({error:'Only executed actions accept outcomes'},422);if(!['SUCCESS','FAILED','UNKNOWN'].includes(b.outcome))return json({error:'Invalid outcome'},422);act.outcome=b.outcome;}
else if(b.op==='import'){if(!Array.isArray(b.rows)||b.rows.length>2000)return json({error:'Import up to 2,000 rows'},422);let accepted=0,duplicates=0;const errors:string[]=[];for(const [idx,r] of b.rows.entries()){if(!r.order_id||!r.customer_id||!r.sku_id||!r.order_date||!Number.isFinite(Date.parse(r.order_date))||!/(Z|[+-]\d\d:\d\d)$/.test(r.order_date)||!['COD','PREPAID','PARTIAL_COD'].includes(r.payment_mode)||!Number.isFinite(Number(r.order_amount_inr))||Number(r.order_amount_inr)<=0||!Number.isInteger(Number(r.quantity))||Number(r.quantity)<1){errors.push(`Row ${idx+2}: check required fields, ISO date with timezone, payment, positive amount and quantity`);continue;}if(state.orders.some(o=>o.id===r.order_id)){duplicates++;continue;}state.orders.push({id:String(r.order_id).slice(0,80),customer:String(r.customer_id).slice(0,80),area:String(r.pincode||'Unknown'),amount:Math.round(Number(r.order_amount_inr)*100),payment:r.payment_mode,status:'IN_TRANSIT',score:0,band:'INSUFFICIENT_DATA',rider:'',day:4,reason:'',attempts:[],source:'SELLER_UPLOADED'});accepted++;}result={accepted,duplicates,errors};}
else return json({error:'Unknown operation'},400);
state.audit.unshift({at:now,text:`${a.role} · ${b.op} · ${b.id||'dataset'}${b.decision?' · '+b.decision:''}`});state.audit=state.audit.slice(0,100);const saved=await db.prepare('UPDATE workspaces SET body=?,version=version+1 WHERE tenant=? AND version=?').bind(JSON.stringify(state),dataTenant,row.version).run();if(!saved.meta.changes)return json({error:'Workspace changed. Refresh and retry.'},409);return json({...result,state:viewState(state,a.role),role:a.role,app_env:'demo',workspace:wid,version:row.version+1});
}catch(e){console.error(e);return json({error:'Unable to save. Your input has been preserved; please retry.'},503);}}
